server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: person

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.demo: TRACE
  file:
    name: logs/miaplicacion.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"